version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: crypto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: crypto_db
    ports:
      - "5433:5432"
    volumes:
      - crypto_pgdata:/var/lib/postgresql/data

volumes:
  crypto_pgdata:
